### PR TITLE
reporthost.py: add {} to Missing:

### PR DESCRIPTION
**Pull request by makefu**
without the tag, the missing attributes are not shown.

### CODE REVIEW

**Comment by savon-noir** [comment]
there is a 0 missing between your brackets. could you please resubmit?

**Comment by makefu** [comment]
hi @savon-noir due to the fact that there is only a single argument i do not think it is necessary in that case to explicitly mark the argument.

sample:
```python
   print("Hello {}!".format("World"))
```

**Comment by bmx0r** [comment]
I made the modification in : https://github.com/bmx0r/python-libnessus/tree/1.0.0.3
python-libnessus==1.0.0.3 is available on pipy
Sorry for the delay ;)

**Comment by makefu** [comment]
thanks and keep up your good work

**Pull request closed without merging**
